// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.18.1
// source: kafka-schemas/auth/messages.proto

package auth

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_AccountCreated MessageType = 0
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "AccountCreated",
	}
	MessageType_value = map[string]int32{
		"AccountCreated": 0,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_kafka_schemas_auth_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_kafka_schemas_auth_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_kafka_schemas_auth_messages_proto_rawDescGZIP(), []int{0}
}

type Base struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Sender  string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Type    MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=auth.MessageType" json:"type,omitempty"`
	Sended  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sended,proto3" json:"sended,omitempty"`
	Data    []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Base) Reset() {
	*x = Base{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafka_schemas_auth_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_schemas_auth_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_kafka_schemas_auth_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Base) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Base) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Base) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_AccountCreated
}

func (x *Base) GetSended() *timestamppb.Timestamp {
	if x != nil {
		return x.Sended
	}
	return nil
}

func (x *Base) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AccountCreatedV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicId string `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Fullname string `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Position string `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *AccountCreatedV1) Reset() {
	*x = AccountCreatedV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kafka_schemas_auth_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountCreatedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreatedV1) ProtoMessage() {}

func (x *AccountCreatedV1) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_schemas_auth_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreatedV1.ProtoReflect.Descriptor instead.
func (*AccountCreatedV1) Descriptor() ([]byte, []int) {
	return file_kafka_schemas_auth_messages_proto_rawDescGZIP(), []int{1}
}

func (x *AccountCreatedV1) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *AccountCreatedV1) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountCreatedV1) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *AccountCreatedV1) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

var File_kafka_schemas_auth_messages_proto protoreflect.FileDescriptor

var file_kafka_schemas_auth_messages_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x2d, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x73, 0x2f,
	0x61, 0x75, 0x74, 0x68, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x01, 0x0a, 0x04, 0x42,
	0x61, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x7d, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x56, 0x31, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x2a, 0x21, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x10, 0x00, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x6f, 0x6c, 0x65, 0x4d, 0x61, 0x78, 0x2f, 0x61, 0x73, 0x79,
	0x6e, 0x63, 0x2d, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x2d, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_kafka_schemas_auth_messages_proto_rawDescOnce sync.Once
	file_kafka_schemas_auth_messages_proto_rawDescData = file_kafka_schemas_auth_messages_proto_rawDesc
)

func file_kafka_schemas_auth_messages_proto_rawDescGZIP() []byte {
	file_kafka_schemas_auth_messages_proto_rawDescOnce.Do(func() {
		file_kafka_schemas_auth_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_kafka_schemas_auth_messages_proto_rawDescData)
	})
	return file_kafka_schemas_auth_messages_proto_rawDescData
}

var file_kafka_schemas_auth_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kafka_schemas_auth_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kafka_schemas_auth_messages_proto_goTypes = []interface{}{
	(MessageType)(0),              // 0: auth.MessageType
	(*Base)(nil),                  // 1: auth.Base
	(*AccountCreatedV1)(nil),      // 2: auth.AccountCreatedV1
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_kafka_schemas_auth_messages_proto_depIdxs = []int32{
	0, // 0: auth.Base.type:type_name -> auth.MessageType
	3, // 1: auth.Base.sended:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kafka_schemas_auth_messages_proto_init() }
func file_kafka_schemas_auth_messages_proto_init() {
	if File_kafka_schemas_auth_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kafka_schemas_auth_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Base); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kafka_schemas_auth_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountCreatedV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kafka_schemas_auth_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kafka_schemas_auth_messages_proto_goTypes,
		DependencyIndexes: file_kafka_schemas_auth_messages_proto_depIdxs,
		EnumInfos:         file_kafka_schemas_auth_messages_proto_enumTypes,
		MessageInfos:      file_kafka_schemas_auth_messages_proto_msgTypes,
	}.Build()
	File_kafka_schemas_auth_messages_proto = out.File
	file_kafka_schemas_auth_messages_proto_rawDesc = nil
	file_kafka_schemas_auth_messages_proto_goTypes = nil
	file_kafka_schemas_auth_messages_proto_depIdxs = nil
}
